name: updatepot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'python3'

      - name: updatepot
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          git config --global user.email "bot@fairbird.com"
          git config --global user.name "fairbird enigma po Bot"
          git config advice.addignoredfile false
          git clean -fd
          git checkout python3
          cd po
          ./updatepot.sh
          cd ..
          git add -u
          git add * || :
          git commit -m "pot update"
          git remote add upstream https://${GITHUB_TOKEN}@github.com/fairbird/enigma2-dreambox.git > /dev/null 2>&1
          git push --quiet upstream python3 || echo "failed to push with error $?"
